Settings:
  Power:
    Shutdown: shutdown -h now
    Restart: reboot
    Lock: slock
  Network: xfce4-terminal -e nmtui
  Sound: xfce4-terminal -e alsamixer
  Packages: xfce4-terminal -e sudo apt update
  Bluetooth: blueman-manager
  Screenshot: import -window root Pictures/image.png
  Displays: arandr
  Appearance: lxappearance
  Repos: /home/gabo/packages/tinytools/tgit/tgit
  Keyboard: /home/gabo/packages/keyboard.sh
  Background: /home/gabo/packages/bg.sh
  Dotfiles:
    vim: codium /home/gabo/.vimrc
    bash: codium /home/gabo/.bashrc
    i3: codium /home/gabo/.i3/config
    userChrome: codium /home/gabo/.mozilla/firefox/9lkm9tdr.default/chrome
    tmenus: codium /home/gabo/tmenus