Settings:
  Power:
    Shutdown: shutdown -h now
    Restart: reboot
    Lock: i3lock-fancy
  Network: xfce4-terminal -e nmtui
  Sound: xfce4-terminal -e alsamixer
  Packages: xfce4-terminal -e aptitude
  Bluetooth: blueman-manager
  Screenshot: flameshot gui
  Displays: arandr
  Background: nitrogen
  Dotfiles:
    vim: codium /home/gabo/.vimrc
    bash: codium /home/gabo/.bashrc
    i3: codium /home/gabo/.i3/config
    userChrome: codium /home/gabo/.mozilla/firefox/9lkm9tdr.default/chrome
    tmenus: codium /home/gabo/tmenus