Settings:
  Power:
    Shutdown: x-terminal-emulator -e 'bash -c "sudo poweroff"'
    Restart: x-terminal-emulator -e 'bash -c "sudo reboot"'
    Lock: xscreensaver-command -lock
  Network: 
    Settings: x-terminal-emulator -e nmtui
    Pi-hole: firefox-esr http://192.168.18.18/admin/index.php
  Sound: x-terminal-emulator -e alsamixer
  Packages: x-terminal-emulator -e 'bash -c "sudo apt update; zsh"'
  Bluetooth: blueman-manager
  Screenshot: scrot '/home/gabo/Pictures/screenshots/%Y-%m-%d-%H_%M_%S.jpg'
  Displays: arandr
  Appearance: lxappearance
  Repos: $HOME/packages/tinytools/tgit/dmenu_tgit
  Keyboard: $HOME/packages/keyboard.sh
  Background: sxiv -t -o $HOME/Pictures/wallpapers | xargs xwallpaper --output eDP-1 --stretch
  Dotfiles:
    vim: codium $HOME/.vimrc
    bash: codium $HOME/.bashrc
    i3: codium $HOME/.i3/config
    userChrome: codium $HOME/.mozilla/firefox/9lkm9tdr.default/chrome
    tmenus: codium $HOME/tmenus
    install-script: codium $HOME/install-script.sh
  Monitor: 
    Weather: x-terminal-emulator -e 'bash -c "curl wttr.in; zsh"'
    Resources: x-terminal-emulator -e 'zsh -c "bpytop; zsh"'
  ssh: x-terminal-emulator -e 'zsh -c "ssh pi@192.168.18.18"'
  About: x-terminal-emulator -e 'zsh -c "neofetch; zsh"'